### ISSUE TITLE
async/await compatible -- reqwest 0.10 alpha

### ISSUE THREAD

**Issue by jnicholls** [wisespace-io/binance-rs#34]
This API would be phenomenal if it were completely async/await ready. reqwest 0.10 now supports it, so it is a natural upgrade to this to start decorating the whole api with async/await.

**Comment by wisespace-io** [comment]
@jnicholls It sounds as a good idea. I am not familiar with the new async/await feature, I can take a look and try to integrate.

**Comment by vorot93** [comment]
I think that at this point it may be better to switch the codebase to [my fork](https://github.com/vorot93/binance-async-rs) since it's fully compatible with async/await and tokio 0.2.

**Comment by wisespace-io** [comment]
@vorot93 I will update the README to refer your fork, so we can give the user the option of sync/async versions. Something that we can also do is what has been done in my another project, https://github.com/wisespace-io/yubico-rs where the sync/async version is in the same repository. 

Do you think it would be too much work to do the same here? Feel free to submit a PR and I can add you as a maintainer, otherwise I can simply refer your async version in the README.

**Comment by vorot93** [comment]
I'd be in favor of unifying the crates into one and making a common organization for various exchange APIs like Binance or [HitBTC](https://github.com/vorot93/hitbtc-rs).

**Comment by canesin** [comment]
Hey guys, we at [Nash](https://nash.io/) are sponsoring a MIT licensed (and forever MIT) project for a Rust based trading SDK (with wrappers in several languages). We will be assigning a full time engineer to be fully dedicated to it and reward contributions. Maybe you bunch have interest in that?

**Comment by jnicholls** [comment]
@canesin I would be very interested to participate in that project.

**Comment by canesin** [comment]
@jnicholls , @vorot93 , @wisespace-io add me in Telegram ( @canesin < FCC > ) and let's do a call. There are a few other contributors that I was planning to invite, I saw @dovahcrow has built atop of this library and that @sebnow and @AlexApps99 have contributed significantly before.

**Comment by dovahcrow** [comment]
@canesin yea I'm happy to merge my async version of binance to this repo.

**Comment by canesin** [comment]
I don't know if @wisespace-io is following this thread: I created a slack for the new project https://join.slack.com/t/openlimitsworkspace/shared_invite/zt-fbtlnsva-fFaHHb2zSdc77Vrk7ayhSw

**Comment by mankinskin** [comment]
Is there any plan for this? @dovahcrow and @vorot93 , I have tried using your crates, but it seemed to be structured differently than this crate, and I couldn't figure out how to use it yet. Also your crates seem to be using a Future based API still, which might not be necessary anymore, since [async/await has been stabalised](https://blog.rust-lang.org/2019/11/07/Async-await-stable.html). Would like to fork this crate here (binance-rs) and try to just stick async in front of every method basically.. but since you have already started, I guess it would make sense to work together. However I don't understand why the async versions are missing a `Market` struct (or `AsyncMarket`), which seemed very central to the sync API.

**Comment by canesin** [comment]
@mankinskin https://github.com/nash-io/openlimits

**Comment by dovahcrow** [comment]
@mankinskin Thanks for your try on the library. `binance-async-rs` is a library built a long time ago when Rust doesn't have `async/await` stabilized. I'm sorry that I personally don't have the bandwidth for updating the code for `binance-async-rs` in the near future. However, I would suggest you have a try on the `openlimits` as @canesin mentioned. It looks like they have the code from `binance-async-rs` and already renovated it with `async/await`.

**Comment by mankinskin** [comment]
Sounds great guys :+1:  Thanks everyone!

**Comment by wisespace-io** [comment]
I am closing this issue as async feature is already provided by a different forks.
